# Generated by Django 3.2.7 on 2021-09-12 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0006_auto_20210912_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='related_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='pics.post'),
        ),
    ]
