# Generated by Django 3.2.7 on 2021-12-02 10:42

import backend.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0013_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjti',
            name='jti',
            field=models.CharField(default=backend.utils.generate_jti, help_text='JWT tokens for the user get revoked when JWT id gets regenerated.', max_length=64, verbose_name='jwt id'),
        ),
    ]
